BUG: subprocess.Popen requres list of arguments to be strings
File "/nfsscratch/PREDICT/johnsonhj/src/BRAINSStandAlone-Linux64-gcc44/NIPYPE/nipype/pipeline/plugins/sge.py", line 42, in _is_pending stderr=subprocess.PIPE)
File "/nfsscratch/PREDICT/opt/epd-7.2-1-rh5-x86_64/lib/python2.7/subprocess.py", line 679, in __init__ errread, errwrite)
File "/nfsscratch/PREDICT/opt/epd-7.2-1-rh5-x86_64/lib/python2.7/subprocess.py", line 1228, in _execute_child raise child_exception
TypeError: execv() arg 2 must contain only strings

This was causing nodes to crash when using SGE.

Simply typecast the integer to a string and the nodes pass.