BUG: initial_moving_transform_com needs default
The initial_moving_transform_com needs to be defaulted
to false in order to maintain backwards compatibility.

When this is not default = False, it results in

initial_moving_transform = <undefined>
initial_moving_transform_com = <undefined>

Error:
Registration requires a value for input 'invert_initial_moving_transform' because one of initial_moving_transform is set. For a list of required inputs, see Registration.help()

Adding try catch block to ensure that conversions occur properly, or use defalut behavior
if boolean is undefined.

File "/Shared/sinapse/sharedopt/20130601/RHEL6/DTIPrep/BRAINSTools-build/NIPYPE/nipype/interfaces/ants/registration.py", line 471, in _format_arg
int(self.inputs.invert_initial_moving_transform))
TypeError: int() argument must be a string or a number, not '_Undefined'