Update registration.py
As of 25 days ago, ANTs now has a "command line robustness" feature (see their PR no.126: https://github.com/stnava/ANTs/pull/126) which forces all provided options to actually mean/do something. This particular option, `--collapse-linear-transforms-to-fixed-image-header`, has been [nonfunctional since December 2012](https://github.com/stnava/ANTs/blame/3b906d86a1b455714983083989417003425cd43c/Examples/antsRegistration.cxx#L76) but is still passed by the nipype interface.

As a result, with a fresh-from-source ANTs build, all nipype.interface.ants.Registration calls now fail with the message:
```
Standard output:
ERROR:  Invalid flag provided collapse-linear-transforms-to-fixed-image-header
Standard error:
ERROR:  Invalid command line flags found! Aborting execution.
Return code: 1
```

There is no provision to turn off this flag; the interface always passes the default of 0 (False). Until this flag actually works again on ANTs' end, we should disable the flag in the registration interface.